variables:
  SECURITY_MONITORING:
    value: "false"
    description: Security monitoring enablement

stages:
  - build
  - quality
  - push
  - post-release

include:
  - ".pipelines/ci.yml"
  - ".pipelines/security.yml"
